### ISSUE TITLE
sleep commands

### ISSUE THREAD

**Issue by EmilioD** [ksperis/autosnap-rbd-shadow-copy#3]
what is the logic behind the different sleep commands in autosnap.sh?
there are several lines that have varying sleep lengths, what are you protecting/accounting for?

**Comment by ksperis** [comment]
The first "sleep 1" is only for the loop, until the enhancement cache (if used) is emptied.
The "sleep 600" in the cleansnapshot function should be no longer needed since recent versions of Ceph. On old versions (<dumpling), the removal of many snapshots at once could imply a heavy load, which could make the cluster unreachable.
The last "sleep 60" before mounting snapshot is only a protection. I don't remember why, but I'm not sure it's still necessary.
